services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JAKOTA\ZernioConnector\:
    resource: '../Classes/*'

  JAKOTA\ZernioConnector\Task\ImportSocialMediaTask:
    public: true
